{
    "name": "Sarya Forecast Analysis",
    "version": "17.0",
    'license': 'AGPL-3',
    "author": "Sarya",
    "website": "www.sarya.com",
    "summary": "Sarya Forecast Analysis",
    "description": """ Sarya Forecast Analysis """,
    "depends": ["base", "stock", "kg_sarya", "product", "report_xlsx"],
    "data": [
             "security/ir.model.access.csv",
             "security/security.xml",
             # "wizard/load_product_wizard_view.xml",
             # "wizard/landed_cost_analysis.xml",
             "reports/report_forecast_xlsx.xml",
             # "reports/report_ytd_view.xml",
             "data/forecast_analysis_ir_crons.xml",
             # "data/forecast_analysis_server_actions.xml",
             # "views/forecast_analysis_view.xml",
             "views/forecast_location_views.xml",
             # "views/sales_budget_view.xml",
             "views/report_email_config_views.xml",
             ],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
}
