{
    "name": "Cha Sarya Sales",
    "version": "17.2.0",
    "category": "API",
    'license': 'AGPL-3',
    "author": "Chandhu",
    "website": "www.sarya.com",
    "summary": "Sarya Sale Customization",
    "support": "chandhu@sarya.ae",
    "description": """Sarya Sale Customization""",
    "depends": ["base", "sale_margin", "kg_sarya", "kg_sarya_vansales", "sry_outlet_coverage_plan"],
    "data": ['security/security.xml',
             'security/ir.model.access.csv',
             'data/cron.xml',
             "views/sale_views.xml",
             "views/picking_print_status.xml",
             "views/sales_stock_report_view.xml"],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
}
