# -*- coding: utf-8 -*-
{
    'name': "Sarya Van Sales",
    'summary': """Used to Communicate with the mobile app.""",
    'description': """Used to Communicate with the mobile app.""",
    'author': "Mini k",
    'website': "www.klystronglobal.com",
    'category': 'Sales',
    'version': '17.2',
    'depends': ['base', 'mail', 'kg_sarya', 'stock', 'kg_sarya_inventory'],
    "license": "AGPL-3",
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/data.xml',
        'views/login_history_views.xml',
        'views/driver_views.xml',
        'views/vehicle_views.xml',
        'views/user_route_views.xml',
        'views/res_partner_views.xml',
        'views/region_views.xml',
        'views/user_shift_views.xml',
        'views/route_planner_views.xml',
        'views/customer_visit_log_views.xml',
        'views/client_asset_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_transfer_request_views.xml',
        'views/sales_return_form_views.xml',
        'views/reason_code_views.xml',
        'wizard/sales_return_wizard_views.xml',
        'views/res_settings_view.xml',
        'data/scheduler.xml',
        # 'views/stock_transfer.xml',
    ],
}
