# -*- coding: utf-8 -*-
from . import data_sync_log
from . import pos_config
from . import pos_session
from . import res_partner
from . import pos_order
from . import pos_order_line
from . import till_assign_and_closure
from . import till_audit_and_closure
from . import till_audit_and_closure_line
from . import cash_statement
from . import res_company
from . import res_config_settings
from . import product_template
from . import account_move
from . import account_move_line
from . import bank_transfer
from . import bank_transfer_line
from . import pos_kitchen_screen_report
