{
    "name": "Cha Sarya Purchase",
    "version": "17.10",
    "category": "API",
    'license': 'AGPL-3',
    "author": "Chandhu",
    "website": "www.sarya.com",
    "summary": "Chandhu Sarya Purchase",
    "support": "chandhu@sarya.ae",
    "description": """Purchase Customization""",
    "depends": ["purchase_stock", "kg_sarya_inventory", "purchase", "account"],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/scheduler.xml',
        'data/mail_template_data.xml',
        'data/data.xml',
        'data/activity.xml',
        'views/res_settings.xml',
        'views/purchase.xml',
        'views/local_purchase.xml',
        'views/res_partner.xml',
        'views/office_purchase.xml',
        'report/report_local_purchase.xml',
        'report/report_office_purchase.xml'
    ],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
}
