{
    "name": "Cha Sarya Account",
    "version": "17.1.1",
    "category": "API",
    'license': 'AGPL-3',
    "author": "Chandhu",
    "website": "www.sarya.com",
    "summary": "Chandhu Sarya Account Customisation",
    "support": "chandhu@sarya.ae",
    "description": """Common Inventory API""",
    "depends": ["account", "kg_sarya", "kg_sarya_rebate", "base"],
    "data": ['security/ir.model.access.csv',
              'security/security.xml',
             'data/ir_sequence_data.xml',
             'data/ewaybill_type_data.xml',
             'wizard/sarya_reconcile_partial_view.xml',
             'wizard/aging_receivable_report.xml',
             'wizard/sarya_reconcile_load_rebate.xml',
             'views/account_payment_views.xml',
             'views/sarya_reconcile_views.xml',
             'views/account_move_views.xml',
             'views/account_bank_statement.xml',
             'views/invoice_screen.xml',
             'views/res_company.xml',
             'views/res_partner.xml',
             'views/res_country_state.xml',
             'views/eway_bill_generation.xml',
             ],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
}
