# -*- coding: utf-8 -*-
{
    'name': "Sarya Inventory",
    'summary': """Inventory customization""",
    'description': """Inventory customization""",
    'author': "MINI K",
    'website': "www.klystronglobal.com",
    'category': 'Inventory',
    'version': '17.1',
    'license': 'AGPL-3',
    'depends': ['base', 'mail', 'stock', 'product', 'sale', 'purchase', 'quality_control',
                'kg_sarya','account', 'mrp'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/cron.xml',
        'data/mail_template.xml',
        'wizard/shipment_advice_receive_qty_partial.xml',
        'views/res_company_view.xml',
        'views/res_config_settings.xml',
        'views/product_reference.xml',
        'views/new_item_code_request.xml',
        'views/product_category.xml',
        'views/manufacturer.xml',
        'views/customer_section.xml',
        'views/sale_package.xml',
        'views/purchase_views.xml',
        'views/product_views.xml',
        'views/shipment_advice_views.xml',
        'views/promotion_entry.xml',
        'views/inspection_view.xml',
        'views/stock_production_lot.xml',
        'views/landed_cost.xml',
        'report/sale_report.xml',
        'report/invoice_porint_out.xml',
        'report/report_picking_inherit.xml',

        'report/internal_transfer_delivery_challan.xml',
        'report/reports_delivery_challan.xml',

        'views/package_type_view.xml',
        'views/stock_move.xml',
        'views/shipment_advice_inspection_date.xml',
        'views/landed_cost_document.xml',
        'views/account_incoterms_view.xml',
        'views/res_partner_view.xml',
        'views/shipment_advice_grn.xml',
        'views/shipment_advice_inspection.xml',
        'views/bl_entry_view.xml',
        'views/shipment_advice_grn_approval.xml',
        'views/shipment_advice_grn_recheck_verification.xml',
        'views/shipment_advice_config_view.xml',
        'views/shipment_advice_eta_report_view.xml',
        'views/inventory_value_history.xml',
        'views/bl_entry_cost.xml',
        'views/mrp_production_view.xml',
        'views/internal_stock_transfer.xml',
        'views/pod.xml',
        'views/stock_location.xml',
        'views/delivery_partner_view.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
}
