from . import attendance_device
from . import attendance_record
from . import config_settings
from . import device_command
from . import operation_log
from . import device_user
from . import fingerprint_template
from . import user_picture
from . import face_template
from . import resource_calendar
from . import fp_status_policy
from . import attendance_process
from . import hr_employee
from . import biometric_data
