# -*- coding: utf-8 -*-

{
    'name': 'Data Sync',
    'description': """Data Sync""",
    'summary': """Data Sync""",
    'version': '17.0.0.0.0',
    'category': 'Point of Sale',
    'sequence': 10,
    'author': 'SHUBIN VS',
    'company': 'Sarya',
    'maintainer': 'Sarya',
    'website': "https://www.sarya.ae",
    # 'support': 'support@sarya.com',
    'depends': ['base', 'point_of_sale', 'product'],
    'data': [
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'security/ir.model.access.csv',
        'views/data_sync_log_view.xml',
        'views/pos_config_view.xml',
        'views/res_partner_view.xml',
        'views/till_assign_and_closure_view.xml',
        'views/till_audit_and_closure_view.xml',
        'views/pos_session_view.xml',
        'views/cash_statement_view.xml',
        'views/bank_transfer_view.xml',
        'views/res_config_settings_view.xml',
        'views/product_template_view.xml',
        'views/pos_kitchen_screen_report_view.xml',
        'views/pos_order_view.xml',
        'views/pos_order_report_view.xml',
        'views/pos_order_type_view.xml',
        'wizard/cash_deposit_wizard_view.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/icon.png'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
